# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rosa Goetz
email: rogoetz@ad.unc.edu
description: This is a test site for INLS 161
author: Rosa Goetz
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rogoetz.github.io/" # the base hostname & protocol for your site
twitter_username:  
github_username:  rogoetz
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
